print("\033[1;33m=-=" * 10)
print("TABUADA")
print('=-=' * 10)
num = int(input('\033[1;30mDigite um numero: '))
print(f"\033[1;97mA TABUADA DE {num}: ")
print('=-=' * 10)
print(f'{num} X 1 = {num * 1}')
print(f'{num} X 2 = {num * 2}')
print(f'{num} X 3 = {num * 3}')
print(f'{num} X 4 = {num * 4}')
print(f'{num} X 5 = {num * 5}')
print(f'{num} X 6 = {num * 6}')
print(f'{num} X 7 = {num * 7}')
print(f'{num} X 8 = {num * 8}')
print(f'{num} X 9 = {num * 9}')
print(f'{num} X 10 = {num * 10}')
print('=-=' * 10)
