print('\033[1;33m=+=' * 15)
print('ANALISANDO NOME')
print('=+=' * 15)
nome = str(input('\033[1;97mDigite seu nome completo: ')).strip()
print(f'ANALISANDO O NOME... {nome}')
print('\033[1;36m=-=' * 15)
print(f'Seu nome em maiusculo: {nome.upper()}')
print(f'Seu nome em minusculo: {nome.lower()}')
print(f'Seu nome tem:  {len(nome) - nome.count(" ")} letras no total')
print(f'Seu primeiro nome tem:  {len(nome.split()[0])} letras no total')
print('=-=' * 15)
